language: rust

cache:
  yarn: true
  cargo: true

rust:
  - stable
  - beta
  - nightly

env:
  matrix:
    - TRAVIS_NODE_VERSION="8"
    - TRAVIS_NODE_VERSION="6"
    - TRAVIS_NODE_VERSION="4"

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux
  - osx

before_install:
  - source $HOME/.nvm/nvm.sh
  - nvm install ${TRAVIS_NODE_VERSION}
  - nvm use ${TRAVIS_NODE_VERSION}
  - ./ci/setup.sh

script:
  - ./ci/test.sh
