[package]
name = "neon-serde"
version = "0.0.1"
authors = ["Gabriel Castro <dev@GabrielCastro.ca>"]
description = "Easily serialize object for use with neon"
license = "MIT"

[dependencies]
serde = "1.*"
error-chain = "0.11.*"
neon = "0.1.*"
cast = "0.2.*"
